import Head from 'next/head';
import Link from 'next/link';
import { useEffect } from 'react';
import { useState } from 'react';
import { useContext } from 'react';
import { Store } from '../utils/Store';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { useSession } from 'next-auth/react';
export default function Layout({ title, children }) {
  const { status, data: session } = useSession();
  const { state } = useContext(Store);
  const { cart } = state;
  const [cartItemsCount, setCartItemsCount] = useState(0);
  useEffect(() => {
    setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
  }, [cart.cartItems]);

  return (
    <>
      <Head>
        <title>{title ? title + ' - Arzu ' : 'Arzu'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer position=" bottom-center" limit={1} />
      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex h-12 justify-between shadow-md items-center px-4">
            <Link href="/">
              <p className="text-2xl font-bold">Arzu</p>
            </Link>
            <div className="hidden sm:flex w-full justify-center space-x-4">
              <Link href={'/category/Basics'}>
                <p>Basics</p>
              </Link>
              <Link href={'/category/Tracksuits'}>
                <p>Tracksuits</p>
              </Link>
              <Link href={'/category/Tunics'}>
                <p>Tunics</p>
              </Link>
              <Link href={'/category/Capri'}>
                <p>Capri</p>
              </Link>
              <Link href={'/category/Shorts'}>
                <p>Shorts</p>
              </Link>
            </div>
            <div className="flex">
              <Link href="/cart">
                <p className="p-2">
                  Cart
                  {cartItemsCount > 0 && (
                    <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                      {cartItemsCount}
                    </span>
                  )}
                </p>
              </Link>
              <div className="p-2">
                {status === 'loading' ? (
                  'Loading'
                ) : session?.user ? (
                  session.user.name
                ) : (
                  <Link href="/login">
                    <p>Login</p>
                  </Link>
                )}
              </div>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex h-10 justify-center items-center shadow-inner">
          Copyright © Arzu 2022
        </footer>
      </div>
    </>
  );
}
