const data = {
  products: [
    {
      name: 'Long-Sleeve gray top',
      category: 'Basics',
      code: 801,
      price: 155,
      slug: '801',
      image: '/images/801.jpeg',
      rating: 4.5,
      countInStock: 20,
      numReviews: 8,
      fabric: '95% Cotton 5% Lycra',
    },
    {
      name: 'gray tank top',
      category: 'Basics',
      code: 802,
      price: 135,
      slug: '802',
      image: '/images/802.jpeg',
      rating: 3,
      countInStock: 10,
      numReviews: 4,
      fabric: '95% Cotton 5% Lycra',
    },
    {
      name: 'black tracksuit',
      category: 'Tracksuits',
      code: 22132,
      price: 380,
      slug: '22132',
      image: '/images/22132.jpeg',
      rating: 4.5,
      countInStock: 20,
      numReviews: 8,
      fabric: '95% Cotton 5% Lycra',
    },
    {
      name: 'purple tracksuit',
      category: 'Tracksuits',
      code: 22133,
      price: 380,
      slug: '22133',
      image: '/images/22133.jpeg',
      rating: 4.5,
      countInStock: 20,
      numReviews: 8,
      fabric: '95% Cotton 5% Lycra',
    },
    {
      name: 'Black Tunic half zipper',
      category: 'Tunics',
      code: 22137,
      price: 410,
      slug: '22137',
      image: '/images/22137.jpeg',
      rating: 4.5,
      countInStock: 20,
      numReviews: 8,
      fabric: '95% Cotton 5% Lycra',
    },
    {
      name: 'Black and leopard Tunic long zipper',
      category: 'Tunics',
      code: 22143,
      price: 410,
      slug: '22143',
      image: '/images/22143.jpeg',
      rating: 4.5,
      countInStock: 20,
      numReviews: 8,
      fabric: '95% Cotton 5% Lycra',
    },
    {
      name: 'pink and baby blue capri set',
      category: 'Capri',
      code: 22304,
      price: 200,
      slug: '22304',
      image: '/images/22304.jpeg',
      rating: 4.5,
      countInStock: 20,
      numReviews: 8,
      fabric: '95% Cotton 5% Lycra',
    },
    {
      name: 'Black and gray parrot capri set',
      category: 'Capri',
      code: 22307,
      price: 200,
      slug: '22307',
      image: '/images/22307.jpeg',
      rating: 4.5,
      countInStock: 20,
      numReviews: 8,
      fabric: '95% Cotton 5% Lycra',
    },
    {
      name: 'Black and mint-green monster shorts set',
      category: 'Shorts',
      code: 22405,
      price: 190,
      slug: '22405',
      image: '/images/22405.jpeg',
      rating: 4.5,
      countInStock: 20,
      numReviews: 8,
      fabric: '95% Cotton 5% Lycra',
    },
    {
      name: 'mint-green and dark-gray snoopy shorts set',
      category: 'Shorts',
      code: 22404,
      price: 190,
      slug: '22404',
      image: '/images/22404.jpeg',
      rating: 4.5,
      countInStock: 30,
      numReviews: 8,
      fabric: '95% Cotton 5% Lycra',
    },
  ],
};

export default data;
